# Generated by Django 5.0.4 on 2024-09-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DESKTOPPACKAGE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('UPS', 'UPS'), ('Mouse', 'Mouse')], default='desktop', max_length=100)),
                ('desktop_SerialNo', models.CharField(max_length=100)),
                ('desktop_BrandName', models.CharField(max_length=100)),
                ('desktop_Model', models.CharField(max_length=100)),
                ('desktop_Processor', models.CharField(max_length=33)),
                ('desktop_Memory', models.CharField(max_length=100)),
                ('desktop_Drive', models.CharField(max_length=332)),
                ('desktop_Graphics', models.CharField(max_length=100)),
                ('desktop_Graphics_Size', models.CharField(max_length=100)),
                ('desktop_OS', models.CharField(max_length=100)),
                ('desktop_Office', models.CharField(max_length=100)),
                ('desktop_OS_keys', models.CharField(max_length=100)),
                ('desktop_Office_keys', models.CharField(max_length=100)),
            ],
        ),
    ]
