# Generated by Django 5.0.4 on 2025-03-14 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disposed', models.BooleanField(default=False)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesktopDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(max_length=255)),
                ('computer_name', models.CharField(max_length=255, null=True, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255, null=True)),
                ('processor', models.CharField(max_length=33, null=True)),
                ('memory', models.CharField(max_length=100, null=True)),
                ('drive', models.CharField(max_length=332, null=True)),
                ('asset_owner', models.CharField(max_length=255, null=True)),
                ('desktop_Graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('desktop_Graphics_Size', models.CharField(blank=True, max_length=100, null=True)),
                ('desktop_OS', models.CharField(blank=True, max_length=100, null=True)),
                ('desktop_Office', models.CharField(blank=True, max_length=100, null=True)),
                ('desktop_OS_keys', models.CharField(blank=True, max_length=100, null=True)),
                ('desktop_Office_keys', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_details', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('docs_PAR', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Propertyno', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Acquisition_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Value', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Datereceived', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Dateinspected', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyboard_sn_db', models.CharField(max_length=255)),
                ('keyboard_brand_db', models.CharField(max_length=255)),
                ('keyboard_model_db', models.CharField(max_length=255)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboards', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('keyboard_dispose_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.keyboarddetails')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('monitor_sn_db', models.CharField(max_length=255)),
                ('monitor_brand_db', models.CharField(max_length=255)),
                ('monitor_model_db', models.CharField(max_length=255)),
                ('monitor_size_db', models.CharField(max_length=255, null=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('monitor_disposed_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.monitordetails')),
            ],
        ),
        migrations.CreateModel(
            name='MouseDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mouse_sn_db', models.CharField(max_length=255, null=True)),
                ('mouse_brand_db', models.CharField(max_length=255, null=True)),
                ('mouse_model_db', models.CharField(max_length=255, null=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_db', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('mouse_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mousedetails')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_owner', models.CharField(max_length=100)),
                ('previous_designation', models.CharField(max_length=100)),
                ('previous_section', models.CharField(max_length=100)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_from', models.CharField(blank=True, max_length=100, null=True)),
                ('transferred_to', models.CharField(max_length=100)),
                ('owner_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_section', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='UPSDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ups_sn_db', models.CharField(max_length=255)),
                ('brand_db', models.CharField(max_length=255)),
                ('model_db', models.CharField(max_length=255)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ups', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedUPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('ups_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.upsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_Asset_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Asset_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Asset_section', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Enduser', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Enduser_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Enduser_section', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package_db', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='inventory.desktop_package')),
            ],
        ),
    ]
