# Generated by Django 5.0.7 on 2024-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('UPS', 'UPS'), ('Mouse', 'Mouse')], default='desktop', max_length=100)),
                ('serialE', models.CharField(max_length=100)),
                ('brandname', models.CharField(max_length=100)),
                ('modelname', models.CharField(max_length=100)),
                ('Parnumber', models.CharField(max_length=33)),
                ('PropertyNumber', models.CharField(max_length=100)),
                ('Purchasedate', models.CharField(max_length=332)),
                ('Computername', models.CharField(max_length=100)),
                ('Windowsversion', models.CharField(max_length=100)),
                ('UnitCost', models.CharField(max_length=100)),
                ('EndUser', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
            ],
        ),
    ]
