# Generated by Django 5.0.4 on 2024-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/'),
        ),
    ]
