# Generated by Django 5.0.4 on 2025-03-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnershipHistory',
        ),
    ]
