# Generated by Django 5.0.4 on 2024-09-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='brandname',
            new_name='desktop_BrandName',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='modelname',
            new_name='desktop_Model',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='serialE',
            new_name='desktop_SerialNo',
        ),
    ]
