# Generated by Django 5.0.4 on 2025-03-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_ownershiphistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnershipTransfer',
        ),
    ]
