# Generated by Django 5.0.4 on 2024-09-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_brandname_equipment_desktop_brandname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Purchasedate',
            new_name='desktop_Drive',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Computername',
            new_name='desktop_Graphics',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Designation',
            new_name='desktop_Graphics_Size',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='EndUser',
            new_name='desktop_Memory',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='PropertyNumber',
            new_name='desktop_OS',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='UnitCost',
            new_name='desktop_OS_keys',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Windowsversion',
            new_name='desktop_Office',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='Parnumber',
            new_name='desktop_Processor',
        ),
        migrations.AddField(
            model_name='equipment',
            name='desktop_Office_keys',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
