# Generated by Django 5.0.4 on 2024-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_desktoppackage_is_disposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktoppackage',
            name='disposal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
