# Generated by Django 5.0.4 on 2024-09-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_desktoppackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktoppackage',
            name='id',
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='id_number',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
