# Generated by Django 5.0.4 on 2024-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_desktoppackage_disposal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Monitor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Monitor_Model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Monitor_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Monitor_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
