# Generated by Django 5.0.4 on 2025-03-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_employee_ownershiphistory_ownershiptransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
