# Generated by Django 5.0.4 on 2024-09-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_desktoppackage_desktop_monitor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktoppackage',
            old_name='desktop_Monitor',
            new_name='desktop_Acquisition_Type',
        ),
        migrations.RenameField(
            model_name='desktoppackage',
            old_name='desktop_Monitor_brand',
            new_name='desktop_Asset_designation',
        ),
        migrations.RenameField(
            model_name='desktoppackage',
            old_name='desktop_Monitor_size',
            new_name='desktop_Asset_owner',
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Asset_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Computer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Dateinspected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Datereceived',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Enduser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Enduser_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Enduser_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Keyboard_SN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Monitor_Brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Monitor_SN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Monitor_Size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Mouse_Brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Mouse_Model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Mouse_SN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_PAR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Propertyno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_UPS_Brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_UPS_Model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_UPS_SN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_Value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_keyboard_Brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktoppackage',
            name='desktop_keyboard_Model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
