# Generated by Django 5.0.4 on 2024-09-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_desktop_monitor_desktoppackage_desktop_acquisition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktoppackage',
            name='desktop_Graphics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktoppackage',
            name='desktop_Graphics_Size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktoppackage',
            name='desktop_OS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktoppackage',
            name='desktop_OS_keys',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktoppackage',
            name='desktop_Office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktoppackage',
            name='desktop_Office_keys',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
