# Generated by Django 5.0.4 on 2025-03-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='employee_status',
        ),
    ]
