# Generated by Django 5.0.4 on 2024-10-05 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_desktoppackage_desktop_graphics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=255, unique=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesktopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('computer_name', models.CharField(max_length=255)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_details', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard_sn', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboards', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.keyboarddetails')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_sn', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.monitordetails')),
            ],
        ),
        migrations.CreateModel(
            name='MouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_sn', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mice', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mousedetails')),
            ],
        ),
        migrations.CreateModel(
            name='UPSDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ups_sn', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ups', to='inventory.desktop_package')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedUPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.upsdetails')),
            ],
        ),
    ]
