# Generated by Django 5.0.4 on 2024-10-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_desktop_package_desktopdetails_keyboarddetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboarddetails',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
    ]
