# Generated by Django 5.0.4 on 2025-03-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_keyboarddetails_keyboard_size_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upsdetails',
            old_name='brand_db',
            new_name='ups_brand_db',
        ),
        migrations.RenameField(
            model_name='upsdetails',
            old_name='model_db',
            new_name='ups_model_db',
        ),
        migrations.AddField(
            model_name='upsdetails',
            name='ups_capacity_db',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
