# Generated by Django 5.0.4 on 2024-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_keyboarddetails_is_disposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop_package',
            name='asset_owner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
