# Generated by Django 5.0.7 on 2025-04-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_Enduser_designation',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user_Enduser_section',
        ),
    ]
