# Generated by Django 5.0.4 on 2024-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_desktopdetails_computer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop_package',
            name='asset_owner',
        ),
        migrations.RemoveField(
            model_name='desktop_package',
            name='computer_name',
        ),
        migrations.AddField(
            model_name='desktopdetails',
            name='asset_owner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desktopdetails',
            name='computer_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
