# Generated by Django 5.0.7 on 2025-04-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_userdetails_user_enduser_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_Assetowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetowner_details', to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_Enduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enduser_details', to='inventory.employee'),
        ),
    ]
