# Generated by Django 5.0.4 on 2024-10-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_desktop_package_asset_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopdetails',
            name='desktop_Graphics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktopdetails',
            name='desktop_Graphics_Size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktopdetails',
            name='desktop_OS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktopdetails',
            name='desktop_OS_keys',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktopdetails',
            name='desktop_Office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='desktopdetails',
            name='desktop_Office_keys',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
