# Generated by Django 5.0.4 on 2024-10-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_desktopdetails_desktop_graphics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposedmouse',
            old_name='mouse',
            new_name='mouse_db',
        ),
        migrations.RemoveField(
            model_name='mousedetails',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='mousedetails',
            name='model',
        ),
        migrations.RemoveField(
            model_name='mousedetails',
            name='mouse_sn',
        ),
        migrations.AddField(
            model_name='mousedetails',
            name='monitor_brand_db',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mousedetails',
            name='monitor_model_db',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mousedetails',
            name='monitor_mouse_sn_db',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mousedetails',
            name='monitor_size_db',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
