# Generated by Django 5.0.7 on 2025-04-01 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_userdetails_user_assetowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='desktop_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.desktop_package'),
        ),
    ]
