# Generated by Django 5.0.7 on 2025-04-02 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_employee_desktop_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='desktop_package',
        ),
        migrations.CreateModel(
            name='EndUserChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.desktop_package')),
                ('new_enduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_enduser_records', to='inventory.employee')),
                ('old_enduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_enduser_records', to='inventory.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='OwnershipHistory',
        ),
        migrations.DeleteModel(
            name='OwnershipTransfer',
        ),
    ]
