# Generated by Django 5.0.4 on 2024-10-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_mouse_disposedmouse_mouse_db_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitordetails',
            old_name='brand',
            new_name='monitor_brand',
        ),
        migrations.RenameField(
            model_name='monitordetails',
            old_name='model',
            new_name='monitor_model',
        ),
        migrations.RenameField(
            model_name='mousedetails',
            old_name='monitor_brand_db',
            new_name='mouse_brand_db',
        ),
        migrations.RenameField(
            model_name='mousedetails',
            old_name='monitor_model_db',
            new_name='mouse_model_db',
        ),
        migrations.RenameField(
            model_name='mousedetails',
            old_name='monitor_mouse_sn_db',
            new_name='mouse_size_db',
        ),
        migrations.RenameField(
            model_name='mousedetails',
            old_name='monitor_size_db',
            new_name='mouse_sn_db',
        ),
    ]
