# Generated by Django 5.0.7 on 2025-04-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_ownershiptransfer_desktop_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserchangehistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enduserchangehistory',
            name='new_enduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_enduser', to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='enduserchangehistory',
            name='old_enduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_enduser', to='inventory.employee'),
        ),
    ]
