# Generated by Django 5.0.4 on 2024-10-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_brand_monitordetails_monitor_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitordetails',
            old_name='desktop_package',
            new_name='desktop_package_db',
        ),
        migrations.RenameField(
            model_name='monitordetails',
            old_name='monitor_brand',
            new_name='monitor_brand_db',
        ),
        migrations.RenameField(
            model_name='monitordetails',
            old_name='monitor_model',
            new_name='monitor_model_db',
        ),
        migrations.RenameField(
            model_name='monitordetails',
            old_name='monitor_sn',
            new_name='monitor_sn_db',
        ),
    ]
