# Generated by Django 5.0.4 on 2024-10-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_rename_desktop_package_monitordetails_desktop_package_db_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mousedetails',
            name='mouse_size_db',
        ),
        migrations.AddField(
            model_name='monitordetails',
            name='monitor_size_db',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
