# Generated by Django 5.0.7 on 2025-04-06 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_enduserchangehistory_changed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOwnerChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.desktop_package')),
                ('new_assetowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_assetowner', to='inventory.employee')),
                ('old_assetowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assetowner', to='inventory.employee')),
            ],
        ),
    ]
