# Generated by Django 5.0.7 on 2025-04-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_assetownerchangehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
