# Generated by Django 5.0.4 on 2024-10-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_mousedetails_mouse_size_db_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upsdetails',
            old_name='brand',
            new_name='brand_db',
        ),
        migrations.RenameField(
            model_name='upsdetails',
            old_name='model',
            new_name='model_db',
        ),
        migrations.RenameField(
            model_name='upsdetails',
            old_name='ups_sn',
            new_name='ups_sn_db',
        ),
    ]
