# Generated by Django 5.0.4 on 2024-10-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_brand_upsdetails_brand_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyboarddetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mousedetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upsdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
