# Generated by Django 5.0.7 on 2025-04-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_desktopdisposed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposedDesktopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('keyboard_disposed', models.BooleanField(default=False)),
                ('mouse_disposed', models.BooleanField(default=False)),
                ('ups_disposed', models.BooleanField(default=False)),
                ('monitor_disposed', models.BooleanField(default=False)),
                ('date_disposed', models.DateTimeField(auto_now_add=True)),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.desktopdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='DesktopDisposed',
        ),
    ]
