# Generated by Django 5.0.7 on 2025-04-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_disposeddesktopdetail_delete_desktopdisposed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposeddesktopdetail',
            name='keyboard_disposed',
        ),
        migrations.RemoveField(
            model_name='disposeddesktopdetail',
            name='monitor_disposed',
        ),
        migrations.RemoveField(
            model_name='disposeddesktopdetail',
            name='mouse_disposed',
        ),
        migrations.RemoveField(
            model_name='disposeddesktopdetail',
            name='ups_disposed',
        ),
    ]
