# Generated by Django 5.0.4 on 2024-10-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_mousedetails_desktop_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposedkeyboard',
            old_name='keyboard',
            new_name='keyboardx',
        ),
    ]
