# Generated by Django 5.0.7 on 2025-04-09 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_disposeddesktopdetail_keyboard_disposed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedmonitor',
            name='disposed_under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposed_monitors', to='inventory.disposeddesktopdetail'),
        ),
    ]
