# Generated by Django 5.0.4 on 2024-10-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_rename_keyboard_disposedkeyboard_keyboardx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboarddetails',
            old_name='brand',
            new_name='keyboard_sn_db',
        ),
        migrations.RenameField(
            model_name='keyboarddetails',
            old_name='keyboard_sn',
            new_name='keyboardbrand',
        ),
        migrations.AlterField(
            model_name='mousedetails',
            name='desktop_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_db', to='inventory.desktop_package'),
        ),
    ]
