# Generated by Django 5.0.7 on 2025-04-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_disposedmonitor_disposal_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposedmonitor',
            old_name='date_disposed',
            new_name='disposal_date',
        ),
    ]
