# Generated by Django 5.0.7 on 2025-04-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_rename_date_disposed_disposedmonitor_disposal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedmonitor',
            name='desktop_package_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors_details', to='inventory.desktop_package'),
        ),
    ]
