# Generated by Django 5.0.4 on 2025-05-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_disposedmonitor_desktop_package_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboarddetails',
            name='keyboard_size_db',
        ),
    ]
