# Generated by Django 5.0.4 on 2025-05-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_keyboarddetails_keyboard_size_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedkeyboard',
            name='desktop_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboards_details', to='inventory.desktop_package'),
        ),
    ]
