# Generated by Django 5.0.4 on 2024-10-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_monitordetails_is_disposed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposedmonitor',
            old_name='monitor',
            new_name='monitor_disposed_db',
        ),
    ]
