# Generated by Django 5.0.4 on 2025-05-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_disposedkeyboard_desktop_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedmonitor',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
