# Generated by Django 5.0.4 on 2024-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_rename_monitor_disposedmonitor_monitor_disposed_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Asset_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Asset_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Asset_section', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Enduser', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Enduser_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_Enduser_section', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='desktoppackage',
            name='desktop_Asset_designation',
        ),
        migrations.RemoveField(
            model_name='desktoppackage',
            name='desktop_Asset_owner',
        ),
        migrations.RemoveField(
            model_name='desktoppackage',
            name='desktop_Asset_section',
        ),
        migrations.RemoveField(
            model_name='desktoppackage',
            name='desktop_Enduser',
        ),
        migrations.RemoveField(
            model_name='desktoppackage',
            name='desktop_Enduser_designation',
        ),
        migrations.RemoveField(
            model_name='desktoppackage',
            name='desktop_Enduser_section',
        ),
    ]
