# Generated by Django 5.0.4 on 2025-05-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_disposedkeyboard_disposed_under'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedmouse',
            name='desktop_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouse_details', to='inventory.desktop_package'),
        ),
        migrations.AddField(
            model_name='disposedmouse',
            name='disposed_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposed_mice', to='inventory.disposeddesktopdetail'),
        ),
    ]
