# Generated by Django 5.0.4 on 2024-10-30 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_userdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='desktop_package_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='inventory.desktop_package'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
