# Generated by Django 5.0.4 on 2025-05-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_disposedmouse_desktop_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedups',
            name='desktop_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ups_details', to='inventory.desktop_package'),
        ),
    ]
