# Generated by Django 5.0.4 on 2024-11-02 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_userdetails_desktop_package_db_alter_userdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
