# Generated by Django 5.0.4 on 2024-11-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_desktopdetails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopdetails',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
    ]
