# Generated by Django 5.0.4 on 2025-05-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_disposedups_disposed_under_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposeddesktopdetail',
            name='desktop_package_number',
        ),
    ]
