# Generated by Django 5.0.4 on 2024-11-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_desktopdetails_is_disposed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposedups',
            old_name='ups',
            new_name='ups_db',
        ),
    ]
