# Generated by Django 5.0.4 on 2025-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_remove_disposeddesktopdetail_desktop_package_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboarddetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
