# Generated by Django 5.0.4 on 2024-11-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_keyboarddetails_created_at_monitordetails_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('docs_PAR', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Propertyno', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Acquisition_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Value', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Datereceived', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Dateinspected', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='inventory.desktop_package')),
            ],
        ),
    ]
