# Generated by Django 5.0.4 on 2025-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_keyboarddetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
