# Generated by Django 5.0.4 on 2024-11-05 00:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_documentsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_from', models.CharField(blank=True, max_length=100, null=True)),
                ('transferred_to', models.CharField(max_length=100)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.desktop_package')),
            ],
        ),
    ]
