# Generated by Django 5.0.4 on 2025-05-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_documentsdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop_package',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='documentsdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
