# Generated by Django 5.0.4 on 2024-11-05 01:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_ownershiptransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_owner', models.CharField(max_length=100)),
                ('previous_designation', models.CharField(max_length=100)),
                ('previous_section', models.CharField(max_length=100)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.desktop_package')),
            ],
        ),
    ]
