# Generated by Django 5.0.4 on 2024-11-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_ownershiphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershiptransfer',
            name='owner_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='owner_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
