# Generated by Django 5.0.4 on 2025-05-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopdetails',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand'),
        ),
    ]
