# Generated by Django 5.0.4 on 2025-05-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_desktopdetails_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='name',
        ),
    ]
