# Generated by Django 5.0.4 on 2025-05-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_rename_brand_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_desktop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_keyboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_monitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_mouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_ups',
            field=models.BooleanField(default=False),
        ),
    ]
