# Generated by Django 5.0.4 on 2025-05-19 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_brand_is_desktop_brand_is_keyboard_brand_is_monitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordetails',
            name='monitor_brand_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand'),
        ),
    ]
