# Generated by Django 5.0.4 on 2025-05-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_monitordetails_monitor_brand_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboarddetails',
            name='keyboard_brand_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand'),
        ),
    ]
