# Generated by Django 5.0.4 on 2025-05-20 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_alter_mousedetails_mouse_brand_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsdetails',
            name='ups_brand_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand'),
        ),
    ]
