# Generated by Django 5.0.4 on 2025-06-09 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_preventivemaintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.preventivemaintenance')),
            ],
        ),
    ]
