# Generated by Django 5.0.4 on 2025-06-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_maintenancechecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='performed_by',
            field=models.CharField(max_length=255),
        ),
    ]
