# Generated by Django 5.0.4 on 2025-06-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_preventivemaintenance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='note_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_9',
            field=models.BooleanField(default=False),
        ),
    ]
