# Generated by Django 5.0.4 on 2025-06-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_preventivemaintenance_note_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='date_accomplished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='end_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
