# Generated by Django 5.0.4 on 2025-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_preventivemaintenance_date_accomplished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop_package',
            name='pm_schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktop_package',
            name='pm_schedule_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
