# Generated by Django 5.0.7 on 2025-06-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_desktop_package_pm_schedule_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_schedule_date', models.DateField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_finance', models.BooleanField(default=False)),
                ('is_construction', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_schedules', to='inventory.desktop_package')),
            ],
        ),
    ]
