# Generated by Django 5.0.7 on 2025-06-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_pm_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pm_schedule',
            name='desktop_package',
        ),
    ]
