# Generated by Django 5.0.7 on 2025-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_remove_pm_schedule_desktop_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pm_schedule',
            name='pm_schedule_date',
        ),
        migrations.AddField(
            model_name='pm_schedule',
            name='pm_schedule_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pm_schedule',
            name='pm_schedule_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
