# Generated by Django 5.0.7 on 2025-06-09 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_remove_pm_schedule_pm_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdetails',
            name='PM_Schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pm_schedule'),
        ),
    ]
