# Generated by Django 5.0.7 on 2025-06-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_documentsdetails_pm_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PM_Schedule',
            new_name='PM_Schedule_1stQuarter',
        ),
        migrations.RemoveField(
            model_name='documentsdetails',
            name='PM_Schedule',
        ),
    ]
