# Generated by Django 5.0.7 on 2025-06-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_documentsdetails_pm_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsdetails',
            old_name='PM_Schedule',
            new_name='PM_Schedule_1stQuarter',
        ),
    ]
