# Generated by Django 5.0.4 on 2025-06-10 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_rename_pm_schedule_documentsdetails_pm_schedule_1stquarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(choices=[('Q1', '1st Quarter'), ('Q2', '2nd Quarter'), ('Q3', '3rd Quarter'), ('Q4', '4th Quarter')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentsdetails',
            name='PM_Schedule_1stQuarter',
        ),
        migrations.CreateModel(
            name='PMSectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.officesection')),
                ('quarter_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='inventory.quarterschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='PM_Schedule_1stQuarter',
        ),
    ]
