# Generated by Django 5.0.7 on 2025-06-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_rename_pm_schedule_documentsdetails_pm_schedule_1stquarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM_Schedule_2ndQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_schedule_start', models.DateField(blank=True, null=True)),
                ('pm_schedule_end', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_finance', models.BooleanField(default=False)),
                ('is_construction', models.BooleanField(default=False)),
                ('is_planning', models.BooleanField(default=False)),
                ('is_quality', models.BooleanField(default=False)),
                ('is_coa', models.BooleanField(default=False)),
                ('is_bac', models.BooleanField(default=False)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('is_ode', models.BooleanField(default=False)),
                ('is_ade', models.BooleanField(default=False)),
                ('is_supply', models.BooleanField(default=False)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_ict', models.BooleanField(default=False)),
                ('is_pio', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PM_Schedule_3rdQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_schedule_start', models.DateField(blank=True, null=True)),
                ('pm_schedule_end', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_finance', models.BooleanField(default=False)),
                ('is_construction', models.BooleanField(default=False)),
                ('is_planning', models.BooleanField(default=False)),
                ('is_quality', models.BooleanField(default=False)),
                ('is_coa', models.BooleanField(default=False)),
                ('is_bac', models.BooleanField(default=False)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('is_ode', models.BooleanField(default=False)),
                ('is_ade', models.BooleanField(default=False)),
                ('is_supply', models.BooleanField(default=False)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_ict', models.BooleanField(default=False)),
                ('is_pio', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PM_Schedule_4thQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_schedule_start', models.DateField(blank=True, null=True)),
                ('pm_schedule_end', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_finance', models.BooleanField(default=False)),
                ('is_construction', models.BooleanField(default=False)),
                ('is_planning', models.BooleanField(default=False)),
                ('is_quality', models.BooleanField(default=False)),
                ('is_coa', models.BooleanField(default=False)),
                ('is_bac', models.BooleanField(default=False)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('is_ode', models.BooleanField(default=False)),
                ('is_ade', models.BooleanField(default=False)),
                ('is_supply', models.BooleanField(default=False)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_ict', models.BooleanField(default=False)),
                ('is_pio', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_ade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_bac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_coa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_ict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_ode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_pio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_planning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pm_schedule_1stquarter',
            name='is_supply',
            field=models.BooleanField(default=False),
        ),
    ]
