# Generated by Django 5.0.4 on 2025-06-10 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_officesection_quarterschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_assignments', to='inventory.desktop_package')),
                ('pm_section_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='inventory.pmsectionschedule')),
            ],
        ),
    ]
