# Generated by Django 5.0.4 on 2025-06-11 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_pmscheduleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='pm_schedule_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='inventory.pmscheduleassignment'),
        ),
    ]
