# Generated by Django 5.0.4 on 2025-06-12 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_preventivemaintenance_pm_schedule_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.officesection'),
        ),
    ]
