# Generated by Django 5.0.4 on 2025-06-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_alter_employee_employee_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
