# Generated by Django 5.0.4 on 2025-06-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_alter_employee_employee_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_office',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_office_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.officesection'),
        ),
    ]
