# Generated by Django 5.0.7 on 2025-06-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_remove_employee_employee_office_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposedmonitor',
            old_name='desktop_package_db',
            new_name='desktop_package',
        ),
        migrations.RenameField(
            model_name='monitordetails',
            old_name='desktop_package_db',
            new_name='desktop_package',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='desktop_package_db',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='desktop_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='inventory.desktop_package'),
        ),
    ]
