# Generated by Django 5.0.7 on 2025-06-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_alter_disposedmonitor_monitor_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedmonitor',
            name='monitor_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
