# Generated by Django 5.0.7 on 2025-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_alter_disposedmonitor_monitor_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
