# Generated by Django 5.0.7 on 2025-06-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_alter_desktopdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
