# Generated by Django 5.0.7 on 2025-06-17 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_alter_mousedetails_id_alter_upsdetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedmonitor',
            name='monitor_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand'),
        ),
    ]
