# Generated by Django 5.0.7 on 2025-06-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_alter_disposedmonitor_monitor_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopdetails',
            name='asset_owner',
        ),
    ]
