# Generated by Django 5.0.4 on 2025-09-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_remove_desktopdetails_asset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
