# Generated by Django 5.0.4 on 2025-09-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_employee_employee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordetails',
            name='monitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='monitor_photos/'),
        ),
    ]
