# Generated by Django 5.0.4 on 2025-09-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_monitordetails_monitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedmonitor',
            name='disposed_photo',
            field=models.ImageField(blank=True, null=True, upload_to='disposed_monitor_photos/'),
        ),
    ]
