# Generated by Django 5.0.4 on 2025-09-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_disposedmonitor_disposed_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedmonitor',
            name='monitor_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
