# Generated by Django 5.0.4 on 2025-09-18 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_alter_disposedmonitor_monitor_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalvagedKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('keyboard_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('keyboard_model', models.CharField(blank=True, max_length=255, null=True)),
                ('salvage_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('desktop_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salvaged_keyboards', to='inventory.desktop_package')),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.keyboarddetails')),
            ],
        ),
        migrations.CreateModel(
            name='SalvagedMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('monitor_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('monitor_model', models.CharField(blank=True, max_length=255, null=True)),
                ('monitor_size', models.CharField(blank=True, max_length=255, null=True)),
                ('salvage_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('desktop_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salvaged_monitors', to='inventory.desktop_package')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.monitordetails')),
            ],
        ),
        migrations.CreateModel(
            name='SalvagedMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('mouse_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('mouse_model', models.CharField(blank=True, max_length=255, null=True)),
                ('salvage_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('desktop_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salvaged_mice', to='inventory.desktop_package')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mousedetails')),
            ],
        ),
        migrations.CreateModel(
            name='SalvagedUPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ups_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('ups_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('ups_model', models.CharField(blank=True, max_length=255, null=True)),
                ('ups_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('salvage_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('desktop_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salvaged_ups', to='inventory.desktop_package')),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.upsdetails')),
            ],
        ),
    ]
