# Generated by Django 5.0.4 on 2025-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0076_salvagedkeyboard_salvagedmonitor_salvagedmouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salvagedkeyboard',
            name='asset_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salvagedkeyboard',
            name='computer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salvagedmonitor',
            name='asset_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salvagedmonitor',
            name='computer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salvagedmouse',
            name='asset_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salvagedmouse',
            name='computer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salvagedups',
            name='asset_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salvagedups',
            name='computer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
