# Generated by Django 5.0.4 on 2025-09-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_salvagedkeyboard_asset_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salvagedmonitor',
            name='is_reassigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salvagedmonitor',
            name='reassigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_monitors', to='inventory.desktop_package'),
        ),
    ]
