# Generated by Django 5.0.4 on 2025-09-19 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0078_salvagedmonitor_is_reassigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalvagedMonitorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('reassigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.desktop_package')),
                ('salvaged_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.salvagedmonitor')),
            ],
        ),
    ]
