# Generated by Django 5.0.4 on 2025-09-19 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_salvagedmonitorhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salvagedkeyboard',
            name='is_reassigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salvagedkeyboard',
            name='reassigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_keyboards', to='inventory.desktop_package'),
        ),
        migrations.CreateModel(
            name='SalvagedKeyboardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('reassigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.desktop_package')),
                ('salvaged_keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.salvagedkeyboard')),
            ],
        ),
    ]
