# Generated by Django 5.0.4 on 2025-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_salvagedups_is_reassigned_salvagedups_reassigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salvagedmonitor',
            name='disposed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salvagedmonitor',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
    ]
