# Generated by Django 5.0.4 on 2025-09-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0083_salvagedmonitor_disposed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salvagedkeyboard',
            name='disposed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salvagedkeyboard',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salvagedmouse',
            name='disposed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salvagedmouse',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salvagedups',
            name='disposed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salvagedups',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
    ]
