# Generated by Django 5.0.4 on 2025-09-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0086_profile_qr_code_profile_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopdetails',
            name='serial_no_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='keyboarddetails',
            name='keyboard_sn_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monitordetails',
            name='monitor_sn_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mousedetails',
            name='mouse_sn_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='upsdetails',
            name='ups_sn_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
