# Generated by Django 5.0.4 on 2025-09-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0087_desktopdetails_serial_no_norm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopdetails',
            name='serial_no_norm',
        ),
        migrations.RemoveField(
            model_name='keyboarddetails',
            name='keyboard_sn_norm',
        ),
        migrations.RemoveField(
            model_name='monitordetails',
            name='monitor_sn_norm',
        ),
        migrations.RemoveField(
            model_name='mousedetails',
            name='mouse_sn_norm',
        ),
        migrations.RemoveField(
            model_name='upsdetails',
            name='ups_sn_norm',
        ),
    ]
