# Generated by Django 5.0.4 on 2025-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0088_remove_desktopdetails_serial_no_norm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopdetails',
            name='serial_no_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
