# Generated by Django 5.2.6 on 2025-09-26 07:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_keyboarddetails_keyboard_sn_norm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disposed', models.BooleanField(default=False)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/laptops')),
                ('pm_schedule_date', models.DateField(blank=True, null=True)),
                ('pm_schedule_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=255)),
                ('serial_no_norm', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True)),
                ('computer_name', models.CharField(max_length=255, null=True, unique=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('drive', models.CharField(blank=True, max_length=255, null=True)),
                ('laptop_OS', models.CharField(blank=True, max_length=100, null=True)),
                ('laptop_Office', models.CharField(blank=True, max_length=100, null=True)),
                ('laptop_OS_keys', models.CharField(blank=True, max_length=100, null=True)),
                ('laptop_Office_keys', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand')),
                ('laptop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_details', to='inventory.laptoppackage')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_disposed', models.DateTimeField(auto_now_add=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.laptopdetails')),
            ],
        ),
    ]
