# Generated by Django 5.2.6 on 2025-09-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_laptoppackage_laptopdetails_disposedlaptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdetails',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='inventory.laptoppackage'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='inventory.laptoppackage'),
        ),
        migrations.AlterField(
            model_name='documentsdetails',
            name='desktop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='inventory.desktop_package'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='desktop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='inventory.desktop_package'),
        ),
    ]
