# Generated by Django 5.2.6 on 2025-09-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0092_documentsdetails_laptop_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptopdetails',
            old_name='serial_no',
            new_name='laptop_sn_db',
        ),
    ]
