# Generated by Django 5.2.6 on 2025-09-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_rename_serial_no_laptopdetails_laptop_sn_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmscheduleassignment',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_assignments', to='inventory.laptoppackage'),
        ),
        migrations.AlterField(
            model_name='pmscheduleassignment',
            name='desktop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_assignments', to='inventory.desktop_package'),
        ),
    ]
