# Generated by Django 5.2.6 on 2025-09-29 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0095_alter_pmscheduleassignment_laptop_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_maintenances', to='inventory.laptopdetails'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='desktop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desktop_maintenances', to='inventory.desktop_package'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='performed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
