# Generated by Django 5.2.6 on 2025-09-29 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0096_preventivemaintenance_laptop_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='inventory.laptopdetails'),
        ),
    ]
