# Generated by Django 5.2.6 on 2025-09-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0097_alter_userdetails_laptop_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='desktop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='inventory.desktop_package'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='inventory.laptoppackage'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='inventory.laptoppackage'),
        ),
    ]
