# Generated by Django 5.2.6 on 2025-09-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_alter_preventivemaintenance_desktop_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmscheduleassignment',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_assignments', to='inventory.laptoppackage'),
        ),
    ]
