# Generated by Django 5.0.4 on 2025-10-02 09:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0099_alter_pmscheduleassignment_laptop_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_sn_db', models.CharField(max_length=255)),
                ('printer_sn_norm', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True)),
                ('printer_model_db', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_type', models.CharField(blank=True, help_text='Inkjet, Laser, Dot Matrix, etc.', max_length=100, null=True)),
                ('printer_color', models.BooleanField(default=True, help_text='Color or Mono')),
                ('printer_duplex', models.BooleanField(default=False, help_text='Duplex/Double-sided capable?')),
                ('printer_resolution', models.CharField(blank=True, help_text='e.g. 1200x1200 dpi', max_length=100, null=True)),
                ('printer_monthly_duty', models.CharField(blank=True, help_text='Recommended monthly duty cycle', max_length=100, null=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desktop_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='inventory.desktop_package')),
                ('printer_brand_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_model', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_monthly_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('disposal_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('disposed_photo', models.ImageField(blank=True, null=True, upload_to='disposed_printer_photos/')),
                ('desktop_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposed_printers', to='inventory.desktop_package')),
                ('disposed_under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposed_printers', to='inventory.disposeddesktopdetail')),
                ('printer_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.printerdetails')),
            ],
        ),
    ]
