# Generated by Django 5.0.4 on 2025-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_printerdetails_disposedprinter'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_printer',
            field=models.BooleanField(default=False),
        ),
    ]
