# Generated by Django 5.0.4 on 2025-10-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_rename_desktop_package_equipment_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedmouse',
            name='disposed_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposed_mice', to='inventory.disposeddesktopdetail'),
        ),
        migrations.AlterField(
            model_name='disposedups',
            name='disposed_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposed_ups', to='inventory.disposeddesktopdetail'),
        ),
    ]
