# Generated by Django 5.0.4 on 2025-10-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0103_alter_disposedmouse_disposed_under_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_laptop',
            field=models.BooleanField(default=False),
        ),
    ]
