# Generated by Django 5.0.4 on 2025-10-10 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0104_brand_is_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disposed', models.BooleanField(default=False)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/printers')),
                ('pm_schedule_date', models.DateField(blank=True, null=True)),
                ('pm_schedule_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='disposedprinter',
            name='equipment_package',
        ),
        migrations.RemoveField(
            model_name='printerdetails',
            name='equipment_package',
        ),
        migrations.AddField(
            model_name='disposedprinter',
            name='printer_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposed_printers', to='inventory.printerpackage'),
        ),
        migrations.AddField(
            model_name='documentsdetails',
            name='printer_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='inventory.printerpackage'),
        ),
        migrations.AddField(
            model_name='printerdetails',
            name='printer_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='inventory.printerpackage'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='printer_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='inventory.printerpackage'),
        ),
    ]
