# Generated by Django 5.2.6 on 2025-10-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0105_printerpackage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='equipment_package',
        ),
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='laptop_package',
        ),
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='maintenance_date',
        ),
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='pm_schedule_assignment',
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='inventory.pmscheduleassignment'),
        ),
        migrations.AlterField(
            model_name='pmsectionschedule',
            name='quarter_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.quarterschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='pmsectionschedule',
            unique_together={('quarter_schedule', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='quarterschedule',
            unique_together={('year', 'quarter')},
        ),
    ]
