# Generated by Django 5.2.6 on 2025-10-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0106_remove_preventivemaintenance_equipment_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='assignment',
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='equipment_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='inventory.equipment_package'),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='inventory.laptoppackage'),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='pm_schedule_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='inventory.pmscheduleassignment'),
        ),
    ]
