# Generated by Django 5.2.6 on 2025-10-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0107_remove_preventivemaintenance_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsectionschedule',
            name='quarter_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='inventory.quarterschedule'),
        ),
    ]
