# Generated by Django 5.0.4 on 2025-10-23 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0108_alter_pmsectionschedule_quarter_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserchangehistory',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.laptoppackage'),
        ),
        migrations.AlterField(
            model_name='enduserchangehistory',
            name='equipment_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment_package'),
        ),
    ]
