# Generated by Django 5.0.4 on 2025-10-23 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0109_enduserchangehistory_laptop_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetownerchangehistory',
            name='laptop_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.laptoppackage'),
        ),
    ]
