# Generated by Django 5.0.4 on 2025-10-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0110_assetownerchangehistory_laptop_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetownerchangehistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Asset Owner Change History', 'verbose_name_plural': 'Asset Owner Change Histories'},
        ),
        migrations.AlterModelOptions(
            name='enduserchangehistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'End User Change History', 'verbose_name_plural': 'End User Change Histories'},
        ),
        migrations.RemoveField(
            model_name='assetownerchangehistory',
            name='equipment_package',
        ),
        migrations.RemoveField(
            model_name='assetownerchangehistory',
            name='laptop_package',
        ),
        migrations.RemoveField(
            model_name='enduserchangehistory',
            name='equipment_package',
        ),
        migrations.RemoveField(
            model_name='enduserchangehistory',
            name='laptop_package',
        ),
        migrations.AddField(
            model_name='assetownerchangehistory',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='assetownerchangehistory',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enduserchangehistory',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='enduserchangehistory',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetownerchangehistory',
            name='new_assetowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_assetowner_history', to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='assetownerchangehistory',
            name='old_assetowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assetowner_history', to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='enduserchangehistory',
            name='new_enduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_enduser_history', to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='enduserchangehistory',
            name='old_enduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_enduser_history', to='inventory.employee'),
        ),
    ]
