# Generated by Django 5.0.4 on 2025-10-29 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0111_alter_assetownerchangehistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_lname', 'employee_fname']},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pm_due', 'PM Maintenance Due'), ('pm_overdue', 'PM Maintenance Overdue'), ('pm_completed', 'PM Maintenance Completed'), ('asset_added', 'New Asset Added'), ('asset_updated', 'Asset Updated'), ('asset_disposed', 'Asset Disposed'), ('employee_added', 'New Employee Added'), ('employee_updated', 'Employee Updated'), ('disposal_pending', 'Disposal Pending Approval'), ('disposal_approved', 'Disposal Approved'), ('system', 'System Notification'), ('warning', 'Warning'), ('info', 'Information')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('link_url', models.CharField(blank=True, help_text='Link to related item', max_length=500, null=True)),
                ('link_text', models.CharField(blank=True, help_text='Text for the link button', max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='inventory_n_user_id_661d51_idx'), models.Index(fields=['notification_type', '-created_at'], name='inventory_n_notific_f91955_idx')],
            },
        ),
    ]
