# Generated by Django 5.0.4 on 2025-11-17 00:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0113_employee_avatar_employee_bio_employee_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeSuppliesPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_disposed", models.BooleanField(default=False)),
                ("disposal_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qr_codes/office_supplies"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="is_office_supplies",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="qr_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="OfficeSuppliesDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplies_sn_db",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "serial_no_norm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("item_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=1)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("is_disposed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "brand_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.brand",
                    ),
                ),
                (
                    "supplies_package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies_details",
                        to="inventory.officesuppliespackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisposedOfficeSupplies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("disposal_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "disposed_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="disposed_supplies_photos/"
                    ),
                ),
                (
                    "supplies_db",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.officesuppliesdetails",
                    ),
                ),
                (
                    "supplies_package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposed_supplies",
                        to="inventory.officesuppliespackage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentsdetails",
            name="office_supplies_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docs",
                to="inventory.officesuppliespackage",
            ),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="office_supplies_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_details",
                to="inventory.officesuppliespackage",
            ),
        ),
    ]
