# Generated by Django 5.0.4 on 2025-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0114_officesuppliespackage_brand_is_office_supplies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopdetails',
            name='desktop_photo',
            field=models.ImageField(blank=True, null=True, upload_to='desktop_photos/'),
        ),
    ]
