# Generated by Django 5.0.4 on 2025-11-18 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0114_officesuppliespackage_brand_is_office_supplies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopdetails',
            name='desktop_photo',
            field=models.ImageField(blank=True, null=True, upload_to='desktop_photos/'),
        ),
        migrations.AddField(
            model_name='documentsdetails',
            name='docs_photo',
            field=models.ImageField(blank=True, null=True, upload_to='document_photos/'),
        ),
        migrations.AddField(
            model_name='keyboarddetails',
            name='keyboard_photo',
            field=models.ImageField(blank=True, null=True, upload_to='keyboard_photos/'),
        ),
        migrations.AddField(
            model_name='mousedetails',
            name='mouse_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mouse_photos/'),
        ),
        migrations.AddField(
            model_name='upsdetails',
            name='ups_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ups_photos/'),
        ),
        migrations.CreateModel(
            name='DocumentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='document_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.documentsdetails')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
