# Generated by Django 5.2.6 on 2025-11-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0115_desktopdetails_desktop_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboarddetails',
            name='keyboard_photo',
            field=models.ImageField(blank=True, null=True, upload_to='keyboard_photos/'),
        ),
        migrations.AddField(
            model_name='mousedetails',
            name='mouse_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mouse_photos/'),
        ),
        migrations.AddField(
            model_name='upsdetails',
            name='ups_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ups_photos/'),
        ),
    ]
