# Generated by Django 5.0.4 on 2025-11-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0115_desktopdetails_desktop_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopdetails',
            name='laptop_photo',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_photoss/'),
        ),
    ]
