# Generated by Django 5.2.6 on 2025-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0115_desktopdetails_desktop_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdetails',
            name='docs_photo',
            field=models.ImageField(blank=True, null=True, upload_to='document_photos/'),
        ),
    ]
