# Generated by Django 5.0.4 on 2025-11-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0118_alter_documentsdetails_docs_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsdetails',
            name='docs_photo',
            field=models.ImageField(blank=True, null=True, upload_to='document_photos/'),
        ),
    ]
