# Generated by Django 5.0.4 on 2025-11-18 07:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0119_alter_documentsdetails_docs_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField()),
                ('task_description', models.TextField()),
                ('has_schedule_times', models.BooleanField(default=False)),
                ('schedule_times', models.JSONField(blank=True, help_text="JSON array of time strings, e.g., ['9 AM', '2 PM', '8 AM', '10 AM', '12 PM', '2 PM', '4 PM']", null=True)),
                ('requires_value_input', models.BooleanField(default=False)),
                ('value_unit', models.CharField(blank=True, help_text="e.g., '°C', '%', etc.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['template', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='PMChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annex_code', models.CharField(choices=[('A', 'Annex A - Datacenter (Daily/Weekly)'), ('B', 'Annex B - Datacenter (Monthly)'), ('C', 'Annex C - Floor/Building Distributors (Weekly)'), ('F', 'Annex F - Datacenter (Semi-Annual)')], max_length=1, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('schedule_note', models.CharField(blank=True, help_text="e.g., 'Mondays - Fridays', '1st week of the month'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PM Checklist Template',
                'verbose_name_plural': 'PM Checklist Templates',
                'ordering': ['annex_code'],
            },
        ),
        migrations.CreateModel(
            name='PMChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_time', models.TimeField(auto_now_add=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='pm_signatures/')),
                ('printed_name', models.CharField(blank=True, max_length=200)),
                ('general_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='PMChecklistItemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('week1', models.BooleanField(default=False)),
                ('week2', models.BooleanField(default=False)),
                ('week3', models.BooleanField(default=False)),
                ('week4', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_completions', models.JSONField(blank=True, help_text="JSON object with time as key and completion status, e.g., {'9 AM': true, '2 PM': false}", null=True)),
                ('problems_encountered', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('recorded_value', models.CharField(blank=True, max_length=100)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='pm_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='pm_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='pm_photos/')),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_completions', to='inventory.pmchecklistcompletion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pmchecklistitem')),
            ],
            options={
                'ordering': ['item__item_number'],
                'unique_together': {('completion', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PMChecklistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('QUARTERLY', 'Quarterly Report'), ('ANNUAL', 'Annual Report')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('annex_filter', models.CharField(blank=True, help_text='Leave blank for all annexes', max_length=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pm_reports/')),
                ('total_checklists', models.IntegerField(default=0)),
                ('completed_checklists', models.IntegerField(default=0)),
                ('pending_checklists', models.IntegerField(default=0)),
                ('overdue_checklists', models.IntegerField(default=0)),
                ('total_issues_found', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PMChecklistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('due_date', models.DateField()),
                ('week_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location', models.CharField(blank=True, help_text='Location of FD/BD', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklists', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='inventory.pmchecklisttemplate')),
            ],
            options={
                'ordering': ['-scheduled_date', 'template'],
            },
        ),
        migrations.AddField(
            model_name='pmchecklistcompletion',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='inventory.pmchecklistschedule'),
        ),
        migrations.AddField(
            model_name='pmchecklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.pmchecklisttemplate'),
        ),
        migrations.CreateModel(
            name='PMIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200)),
                ('issue_description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('item_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inventory.pmchecklistitemcompletion')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pmchecklistschedule',
            index=models.Index(fields=['scheduled_date', 'status'], name='inventory_p_schedul_d52fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='pmchecklistschedule',
            index=models.Index(fields=['due_date', 'status'], name='inventory_p_due_dat_bef95e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pmchecklistitem',
            unique_together={('template', 'item_number')},
        ),
    ]
