# Generated by Django 5.2.6 on 2025-11-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0117_documentphoto'),
        ('inventory', '0120_pmchecklistitem_pmchecklisttemplate_and_more'),
    ]

    operations = [
    ]
