# Generated by Django 5.0.4 on 2025-11-20 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0121_merge_20251118_2037"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentDowntimeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurrence_date",
                    models.DateField(help_text="Date when downtime occurred"),
                ),
                ("start_time", models.TimeField(help_text="When the downtime started")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="When service was restored (leave blank if ongoing)",
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, help_text="Total downtime in minutes", null=True
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(
                        help_text="e.g., Main Server, UPS Unit A, AC Unit 2",
                        max_length=200,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor - No service impact"),
                            ("MODERATE", "Moderate - Partial impact"),
                            ("MAJOR", "Major - Significant impact"),
                            ("CRITICAL", "Critical - Complete service loss"),
                        ],
                        default="MODERATE",
                        max_length=10,
                    ),
                ),
                (
                    "cause_description",
                    models.TextField(help_text="What caused the downtime?"),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, help_text="How was it resolved?"),
                ),
                (
                    "services_affected",
                    models.TextField(
                        blank=True, help_text="Which services/systems were impacted?"
                    ),
                ),
                (
                    "users_affected_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Approximate number of users affected",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requires_followup", models.BooleanField(default=False)),
                ("followup_notes", models.TextField(blank=True)),
                (
                    "item_completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downtime_events",
                        to="inventory.pmchecklistitemcompletion",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_downtime_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurrence_date", "-start_time"],
                "indexes": [
                    models.Index(
                        fields=["-occurrence_date"],
                        name="inventory_e_occurre_7c61e9_idx",
                    ),
                    models.Index(
                        fields=["equipment_name"], name="inventory_e_equipme_d3c84f_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="inventory_e_severit_fd6281_idx"
                    ),
                ],
            },
        ),
    ]
