# Generated by Django 5.0.4 on 2025-11-24 02:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0122_equipmentdowntimeevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SNMRAreaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "SNMR Area Category",
                "verbose_name_plural": "SNMR Area Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SNMRReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)]
                    ),
                ),
                ("region", models.CharField(default="Region VIII", max_length=100)),
                (
                    "office",
                    models.CharField(
                        default="DPWH Leyte 4th District Engineering", max_length=200
                    ),
                ),
                (
                    "address",
                    models.CharField(default="Ormoc City Leyte", max_length=300),
                ),
                ("network_admin_name", models.CharField(max_length=200)),
                ("network_admin_contact", models.CharField(max_length=100)),
                ("network_admin_email", models.EmailField(max_length=254)),
                ("noted_by_name", models.CharField(max_length=200)),
                (
                    "noted_by_position",
                    models.CharField(default="District Engineer", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="snmr_reports/pdf/"
                    ),
                ),
                (
                    "excel_file",
                    models.FileField(
                        blank=True, null=True, upload_to="snmr_reports/excel/"
                    ),
                ),
                ("is_finalized", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_snmr_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="SNMREntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.PositiveIntegerField()),
                ("status", models.CharField(default="Up and working", max_length=200)),
                ("reason", models.TextField(blank=True, default="N/A")),
                ("initial_isolation", models.TextField(blank=True, default="N/A")),
                ("date", models.CharField(blank=True, default="N/A", max_length=200)),
                ("resolution", models.TextField(blank=True, default="N/A")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snmr_entries",
                        to="inventory.snmrareacategory",
                    ),
                ),
                (
                    "downtime_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snmr_entries",
                        to="inventory.equipmentdowntimeevent",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="inventory.snmrreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "SNMR Entry",
                "verbose_name_plural": "SNMR Entries",
                "ordering": ["report", "item_number"],
            },
        ),
        migrations.AddIndex(
            model_name="snmrreport",
            index=models.Index(
                fields=["-year", "-month"], name="inventory_s_year_89b8f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="snmrreport",
            unique_together={("month", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="snmrentry",
            unique_together={("report", "item_number")},
        ),
    ]
