# Generated by Django 5.2.8 on 2025-11-24 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0123_snmrareacategory_snmrreport_snmrentry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ASIRReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)]
                    ),
                ),
                ("region", models.CharField(default="VIII", max_length=100)),
                (
                    "office",
                    models.CharField(
                        default="DPWH, Leyte Fourth District Engineering Office",
                        max_length=200,
                    ),
                ),
                (
                    "address",
                    models.CharField(default="Ormoc City, Leyte", max_length=300),
                ),
                (
                    "network_admin_name",
                    models.CharField(default="BOBBY L. YU", max_length=200),
                ),
                (
                    "network_admin_contact",
                    models.CharField(default="09219290909", max_length=100),
                ),
                (
                    "network_admin_email",
                    models.EmailField(default="yu.bobby@dpwh.gov.ph", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_finalized", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_asir_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ASIR Report",
                "verbose_name_plural": "ASIR Reports",
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="ASIREntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.PositiveIntegerField()),
                ("application_name", models.CharField(max_length=300)),
                ("number_of_users", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Deployed and being used", "Deployed and being used"),
                            (
                                "Deployed but not being used",
                                "Deployed but not being used",
                            ),
                            ("Down", "Down"),
                            ("Under Maintenance", "Under Maintenance"),
                        ],
                        default="Deployed and being used",
                        max_length=100,
                    ),
                ),
                ("activity_details", models.TextField(blank=True, default="None")),
                (
                    "activity_date",
                    models.CharField(blank=True, default="N/A", max_length=200),
                ),
                ("remarks", models.TextField(blank=True, default="None")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="inventory.asirreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "ASIR Entry",
                "verbose_name_plural": "ASIR Entries",
                "ordering": ["report", "item_number"],
                "unique_together": {("report", "item_number")},
            },
        ),
    ]
