# Generated by Django 5.2.8 on 2025-11-25 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0124_asirreport_asirentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HDRReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)]
                    ),
                ),
                ("region", models.CharField(default="VIII", max_length=100)),
                (
                    "office",
                    models.CharField(
                        default="DPWH Leyte 4th Engineering District", max_length=200
                    ),
                ),
                (
                    "address",
                    models.CharField(default="Ormoc City Leyte", max_length=300),
                ),
                (
                    "network_admin_name",
                    models.CharField(default="BOBBY L. YU", max_length=200),
                ),
                (
                    "network_admin_contact",
                    models.CharField(default="66800|09219290909", max_length=100),
                ),
                (
                    "network_admin_email",
                    models.EmailField(default="yu.bobby@dpwh.gov.ph", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_finalized", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hdr_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HDR Report",
                "verbose_name_plural": "HDR Reports",
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="HDREntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_number", models.CharField(max_length=50)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("Service Request", "Service Request"),
                            ("Incident", "Incident"),
                            ("Change Request", "Change Request"),
                        ],
                        default="Service Request",
                        max_length=100,
                    ),
                ),
                (
                    "main_category",
                    models.CharField(
                        choices=[
                            ("Hardware", "Hardware"),
                            ("Software", "Software"),
                            ("Services", "Services"),
                            ("Network", "Network"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sub_category", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("Done", "Done"),
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("date_reported", models.DateField()),
                ("reported_by", models.CharField(max_length=200)),
                ("resolution", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="inventory.hdrreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "HDR Entry",
                "verbose_name_plural": "HDR Entries",
                "ordering": ["report", "date_reported", "ref_number"],
            },
        ),
    ]
