# Generated by Django 5.0.4 on 2026-03-31 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0127_add_extended_jobsheet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdowntimeevent',
            name='system_reference',
            field=models.CharField(blank=True, help_text='e.g. PC-007, Laptop-Admin-01, Server Room UPS', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentdowntimeevent',
            name='item_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_events', to='inventory.pmchecklistitemcompletion'),
        ),
        migrations.AlterField(
            model_name='hdrentry',
            name='incident_type',
            field=models.CharField(choices=[('Service Request', 'Service Request'), ('Failure', 'Failure')], default='Service Request', max_length=100),
        ),
        migrations.AlterField(
            model_name='hdrentry',
            name='main_category',
            field=models.CharField(choices=[('Business Apps', 'Business Apps'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Services', 'Services')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hdrentry',
            name='status',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('For Repair', 'For Repair'), ('For disposal', 'For disposal')], default='Pending', max_length=50),
        ),
    ]
